/* *****************************************************************************
 * 
 * This file is a part of the Restad project
 * https://sourceforge.net/projects/restad/
 * Author : Yoann Moreau (moreau.yo * at * gmail.com)
 *
 * Copyright (C) 2012 LIA (www.lia.univ-avignon.fr)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * 
 ******************************************************************************/

/*!
  \mainpage
  Restad (Relational Storage for Tagged Documents) is an indexing-querying tool for tagged documents
  using a relational database for storage and querying.
  It actually uses PostgreSQL because it's "the world's most advanced open source database".
  Restad has been developped by the <a href="http://www.lia.univ-avignon.fr/">Computer Science lab of the university of Avignon.</a>

  \section dwnlds Download and install
  To download the tool, see the <a href="https://sourceforge.net/projects/restad/files/">download page</a>.
  See \ref install for details.

  \section dvlpers Contribute to the project
  Restad is open-source and anyone can contribute or fork and edit code to fit to special needs.
  See \ref developers.

  Project website : http://restad.sourceforge.net <br/>
  Project on sourceforge : https://sourceforge.net/projects/restad/
  \author Yoann Moreau (moreau.yo * at * gmail.com)
  \version 0.1.0

  */

/*!
  \page install Install guide

  \section debian Ubuntu/Debian
  Restad needs the following packages :
  \code
libpq-dev qt4-dev-tools
  \endcode

  In the root directory, run
  \code
qmake CONFIG+=release
  \endcode
  then
  \code
make
  \endcode
  The binary files are procuced in bin directory.
  */

// Code groups, to sort classes in the doc
/*!
  \defgroup global Global code used by all commands
  \defgroup exceptions Exceptions of the project
  \defgroup commands Code managing the command line interfaces
  \defgroup preparser Code for the preparsing task
  \defgroup parser Code for the parsing/indexing task
  */

/*!
  \page developers Developer guide
  Restad uses Qt and its qmake/project-file system.
    - The restad.pro file is managing the whole project, but each command has its own project file (in src dir).
    - global.pri is included by all other project file
    - Most of the source files are included by src.pri,
      because they may be used in the final bin file or in the test bin file. Any class which is used by
      more than one project file must be included in src.pri instead of the project file. A class in src.pri
      must include classes which are also in src.pri or it will get linking errors.

  Code documentation is generated by Doxygen, the config file is Doxyfile. Simply run doxygen in the
  project root dir and everything is created/updated in doc/html.

  The project has some test units, see \ref tests.

  If you want to contribute, you can check \ref todo.
  The project uses Git. You can browse the code here https://sourceforge.net/p/restad/code/ .
  The classes of the project are grouped in subdirs, which are represented as modules in this doc, see
  <a href="./modules.html">Modules section</a>.
  Here is a raw class diagram used as a draw of the project, not up to date, not true UML but gives an overview of classes.
  \image html class_diagram.png Class diagram

  */

/*!
  \page tests Tests
  Restad project uses the Qt and CuteTest (https://bitbucket.org/mayastudios/cutetest/overview)
  for testing, you'll need to install both, and specify in test/test.pro the path for CuteTest
  includes and libraries.
  You will need to compile with qmake CONFIG+=debug CONFIG-=release for the test part.

  To test Restad with a database, a Ruby script is doing the job (test/test_index.rb), it needs the pg gem
  and an empty database set up with Restad schema. Just pass a restad-config file as argument and run the
  script into the target directory (i.e. where the Restad bin files are).

  */
